config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'
  resources :infos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/info.rb
class Info < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :infos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]

  def index
    @infos = Info.all
  end
  def show
  end

  def new
    @info = current_user.infos.build
  end

  def edit
  end


  def create
    @info = current_user.infos.build(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: 'Info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:first_name, :last_name, :phone_number, :adress, :state, :zipcode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<%= link_to "New Info", new_info_path %>

app/views/infos/_form.html.erb
<%= form_for(info) do |f| %>
  <% if info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing Info</h1>

<%= render 'form', info: @info %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Infos</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th>address</th>
      <th>State</th>
      <th>zip_code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= info.first_name %></td>
        <td><%= info.last_name %></td>
        <td><%= info.phone_number %></td>
        <td><%= info.address %></td>
        <td><%= info.state %></td>
        <td><%= info.zip_code %></td>
        <td><%= link_to 'Show', info %></td>
        <td><%= link_to 'Edit', edit_info_path(info) %></td>
        <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New Info</h1>

<%= render 'form', info: @info %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @info.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @info.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @info.phone_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @info.address %>
</p>

<p>
  <strong>State:</strong>
  <%= @info.state %>
</p>

<p>
  <strong>Zip_code:</strong>
  <%= @info.zip_code %>
</p>

<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>

app/views/layouts/_loging.html.erb
<% if user_signed_in? %>
  <%= link_to current_user.email, edit_user_registration_path %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { confirm: "are you sure?"} %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign Up", new_user_registration_path %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AtmProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render "layouts/loging" %>

<%= yield %>

  </body>
</html>